### ISSUE TITLE
Realtime work graph

### ISSUE THREAD

**Issue by Wendelstein7** [Lemmmy/KristWeb#19]
enhancement: I desperately need a refresh button. For the whole page, or at least for the work graph. Using browser refresh will lose the session, and have me to enter the main password again.
The way you can currently doing it is by switching screens using the sidebar menu...

But I want a refresh button, or well, maybe live refresh feed of the graph.

**Comment by Lemmmy** [comment]
KristWeb will soon be realtime when the Krist API supports more realtime features. For now, I'll modify this to make the work graph realtime.
