### ISSUE TITLE
Important: Recipient can't be a name

### ISSUE THREAD

**Issue by FixFury** [Lemmmy/KristWeb#20]
When entering names (with and without .kst) in the Recipient textbox they won't stay there, as soon as you click another object, eg the message textbox or the send button, the textbox gets emptied. It's literally impossible to send krist to a name. The "add xxxx" option also doesn't show up anymore like it used to.

**Comment by Lemmmy** [comment]
Please don't be snarky in bugreports.

**Comment by Lemmmy** [comment]
Cannot reproduce.

**Comment by FixFury** [comment]
Alright, by enter it keeps it. Maybe you should notify users that enter pressing is needed. I usually see the enter as the action button for a dialog, so enter means "send" for me, but in this case it thus "accepts" the textbox, which I am unfamiliar with, and so may others.
