### ISSUE TITLE
Locked out of wallet

### ISSUE THREAD

**Issue by TripyVOX** [Lemmmy/KristWeb#21]
I am locked out of my Krist wallet: kli735guo4
It tells me that I do not have access to it. 
On the forum I am Tripy998, and I can pull screenshots from PM and the forum post of me using the address.
I kinda want all my Krist from that wallet.... It's alot.

**Comment by TripyVOX** [comment]
@Lemmmy

**Comment by Lemmmy** [comment]
Hi. This was a security measure to protect insecure wallets from theft. Please contact '3d6' on the ComputerCraft forums for help getting unlocked. Thank you! :)

**Comment by TripyVOX** [comment]
Hey, it's been over a month, and 3d6 has yet to respond or acknowledge my request...

**Comment by TripyVOX** [comment]
@Lemmmy

**Comment by Lemmmy** [comment]
Hi @TripyVOX, I am very sorry about that - I was not aware that 3d6 has not replied. I have unlocked your wallet, please move your funds to a more secure address immediately.

**Comment by TripyVOX** [comment]
Oki dokes. Thank you!

**Comment by TripyVOX** [comment]
@Lemmmy Got them! Thanks! ^^
