### ISSUE TITLE
"MAX" button value not updated/synced with the krist node

### ISSUE THREAD

**Issue by Wendelstein7** [Lemmmy/KristWeb#25]
The value that the MAX button will set the value box to (and also the value at which the "Are you sure you want to send ALL of your monies" message box is shown) are not synced with the krist node and therefore will be inconsistent to the numbers that are and outdated.

**Comment by Lemmmy** [comment]
They should be synced - are you sure your websocket connection isn't spotty?

https://github.com/Lemmmy/KristWeb/blob/46f69fe9d5bfd2385483c924cc968943bc3427c1/src/js/application/websockets.js#L97

**Comment by Wendelstein7** [comment]
Ah yes, that may be the case, as I had kristweb open for a while, so the connection may have dropped somewhere!
