### ISSUE TITLE
Work graph tooltip ghosts when a block is mined

### ISSUE THREAD

**Issue by apemanzilla** [Lemmmy/KristWeb#32]
When a block is mined, the chart refreshes and if a tooltip is showing, it's not removed, leading to this.

![Screenshot](https://i.imgur.com/lurn1pQ.png)

**Comment by Wendelstein7** [comment]
I can confirm, if needed :)

**Comment by hugeblank** [comment]
This also happens on mobile, however it only puts whatever the tooltip was in the least recent section of the graph in the top left screen, and then locks it there.

Additionally the time that was currently selected stays on screen even though the graph is not. This however may want to be reported as a different issue.
![3dd39e00-d2c6-4440-aac2-4dfee9f0c3e0](https://user-images.githubusercontent.com/16393543/39108597-e5732718-467d-11e8-9395-3970b567d1b9.png)

**Comment by Lemmmy** [comment]
Fixed by 89425fb.

**Comment by Lemmmy** [comment]
@hugeblank If this still happens after 1.0.16, make a separate issue.
